KeycloakSettings:
    Authority: "http://server.arkhipenko.lan/keycloak/realms/aid-kit-realm"
    MetadataAddress: "http://server.arkhipenko.lan/keycloak/realms/aid-kit-realm/.well-known/openid-configuration"
    IsRequireHttpsMetadata: false
    IsValidateIssuer: true
    ValidIssuers:
        - "http://server.arkhipenko.lan/keycloak/realms/aid-kit-realm"
    IsValidateAudience: true
    ValidAudiences:
        - "dictionary-service-client"
    ServiceSettings:
        Service: "dictionary-service-client"

DatabaseSettings:
    CommandTimeout: 30000

ConnectionStrings:
    DictionaryDb: "Host=aid-kit.arkhipenko.lan;Port=60001;Database=aid_kit_db;Username=application_user;Password=application_user"